// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Search.Data.Context;

namespace Search.Data.Migrations
{
    [DbContext(typeof(SearchContext))]
    [Migration("20190106193650_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Search.Data.Models.SearchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("SearchTime");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("SearchEntities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SearchEntity");
                });

            modelBuilder.Entity("Search.Data.Models.TicketSearchEntity", b =>
                {
                    b.HasBaseType("Search.Data.Models.SearchEntity");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<DateTime?>("DateFrom");

                    b.Property<DateTime?>("DateTo");

                    b.Property<decimal?>("MaxPrice");

                    b.Property<decimal?>("MinPrice");

                    b.ToTable("TicketSearchEntity");

                    b.HasDiscriminator().HasValue("TicketSearchEntity");
                });

            modelBuilder.Entity("Search.Data.Models.UserSearchEntity", b =>
                {
                    b.HasBaseType("Search.Data.Models.SearchEntity");

                    b.Property<double?>("MinRating");

                    b.ToTable("UserSearchEntity");

                    b.HasDiscriminator().HasValue("UserSearchEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
