/**
 * Chat
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type BackgroundColorType = 0 | 1 | 2;

export const BackgroundColorType = {
    NUMBER_0: 0 as BackgroundColorType,
    NUMBER_1: 1 as BackgroundColorType,
    NUMBER_2: 2 as BackgroundColorType
};
