/**
 * Chat
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BackgroundColorType } from './backgroundColorType';



export interface Settings {
  [key: string]: any;


    id?: string;
    backgroundColor: BackgroundColorType;
    sound: boolean;
    toast: boolean;
    tab: boolean;
    viewTimestampsMessage: boolean;
    hideChat: boolean;
    historyCountsMessages: number;
    disablePrivateMessages: boolean;
}
