/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Severity } from './severity';


export interface NotificationMessage {
  [key: string]: any;


    creator?: string;
    title?: string;
    text?: string;
    severity: Severity;
}
