/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from './encoder';

import { OAuthService } from 'angular-oauth2-oidc';

import { Observable } from 'rxjs';

import { EmailNotification } from '../../models/notification/emailNotification';

import { BASE_NOTIFICATION_PATH, COLLECTION_FORMATS, NotificationInjector }                     from './variables';
import { Configuration }                                     from './configuration';


@Injectable()
export class EmailNotificationService {

    protected basePath = 'http://localhost:5002';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() configuration: Configuration, private oauthService: OAuthService) {
      let basePath: string = NotificationInjector.get(BASE_NOTIFICATION_PATH);
      if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param uname
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailNotificationConfirmRegistration(uname: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public emailNotificationConfirmRegistration(uname: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public emailNotificationConfirmRegistration(uname: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public emailNotificationConfirmRegistration(uname: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uname === null || uname === undefined) {
            throw new Error('Required parameter uname was null or undefined when calling emailNotificationConfirmRegistration.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.post(`${this.basePath}/notification/email/registration/confirmation/${encodeURIComponent(String(uname))}`,
            null,
            {
                headers: this.getHeaders(),
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailNotificationGetAllEmailNotifications(observe?: 'body', reportProgress?: boolean): Observable<Array<EmailNotification>>;
    public emailNotificationGetAllEmailNotifications(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EmailNotification>>>;
    public emailNotificationGetAllEmailNotifications(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EmailNotification>>>;
    public emailNotificationGetAllEmailNotifications(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.get<Array<EmailNotification>>(`${this.basePath}/notification/email/all`,
            {
                headers: this.getHeaders(),
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailNotificationGetEmailNotifications(id: string, observe?: 'body', reportProgress?: boolean): Observable<Array<EmailNotification>>;
    public emailNotificationGetEmailNotifications(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EmailNotification>>>;
    public emailNotificationGetEmailNotifications(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EmailNotification>>>;
    public emailNotificationGetEmailNotifications(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling emailNotificationGetEmailNotifications.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];

        return this.httpClient.get<Array<EmailNotification>>(`${this.basePath}/notification/email/users/${encodeURIComponent(String(id))}`,
            {
                headers: this.getHeaders(),
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    private getHeaders() {
      const token = this.oauthService.getAccessToken();
      return !!token
        ? new HttpHeaders({
            Authorization: 'Bearer ' + token
          })
        : new HttpHeaders();
    }

}
