// <auto-generated />
using System;
using Logging.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Logging.Data.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20190128210000_AddServiceNameToErrorLogDbModel")]
    partial class AddServiceNameToErrorLogDbModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Logging.Data.DbModels.AccountLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EventDate");

                    b.Property<int>("Type");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("AccountLogEntries");
                });

            modelBuilder.Entity("Logging.Data.DbModels.InternalErrorLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("ExceptionType");

                    b.Property<int>("HResult");

                    b.Property<string>("InnerExceptionString");

                    b.Property<string>("Message");

                    b.Property<string>("ServiceName");

                    b.Property<string>("Source");

                    b.Property<string>("StackTrace");

                    b.Property<string>("TargetSiteName");

                    b.HasKey("Id");

                    b.ToTable("InternalErrorLogEntries");
                });

            modelBuilder.Entity("Logging.Data.DbModels.PaymentLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("RecieverId");

                    b.Property<string>("SenderId");

                    b.Property<double>("Transfer");

                    b.HasKey("Id");

                    b.ToTable("PaymentLogEntries");
                });

            modelBuilder.Entity("Logging.Data.DbModels.SearchQueryLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("FilterInfo");

                    b.Property<string>("SearchCriterium");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("SearchQueryLogEntries");
                });

            modelBuilder.Entity("Logging.Data.DbModels.TicketActionLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("TicketId");

                    b.Property<int>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("TicketActionLogEntries");
                });

            modelBuilder.Entity("Logging.Data.DbModels.TicketDealLogEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("OwnerId");

                    b.Property<double?>("Price");

                    b.Property<string>("RecieverId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("TicketDealLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
